version: "2"
run:
  tests: false
linters:
  enable:
    - gofmt
    - govet
    - revive
    - staticcheck
    - unused
    - gosimple
    - ineffassign
  exclusions:
    generated: lax
    presets:
      - common-false-positives
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
