linters:
  enable:
    - gofmt
    - govet
    - revive
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    enable-all: true
  revive:
    severity: warning
    rules:
      - name: var-naming
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false

run:
  timeout: 5m
  go: "1.23"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
